services:
  terminal42_password_validation.listener.regexp:
    class: Terminal42\PasswordValidationBundle\EventListener\PasswordRegexpListener
    public: true
    arguments:
      ['@terminal42_password_validation.validator_manager', '@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.listener.history_log:
    class: Terminal42\PasswordValidationBundle\EventListener\PasswordHistoryListener
    public: true
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.listener.invalid_attempts:
    class: Terminal42\PasswordValidationBundle\EventListener\InvalidAttemptsListener
    public: true
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.listener.password_change:
    class: Terminal42\PasswordValidationBundle\EventListener\PasswordChangeListener
    public: true
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.listener.no_password_change_page_warning:
    class: Terminal42\PasswordValidationBundle\EventListener\NoPwChangePageWarning
    public: true
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.validator_configuration:
    class: Terminal42\PasswordValidationBundle\Validation\ValidationConfiguration

  terminal42_password_validation.validator_manager:
    class: Terminal42\PasswordValidationBundle\Validation\ValidatorManager

  terminal42_password_validation.validator.password_history:
    class: Terminal42\PasswordValidationBundle\Validation\Validator\PasswordHistory
    tags:
      - { name: terminal42_password_validation.validator, alias: password_history }
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.validator.minimum_length:
    class: Terminal42\PasswordValidationBundle\Validation\Validator\MinimumLength
    tags:
      - { name: terminal42_password_validation.validator, alias: minimum_length }
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.validator.maximum_length:
    class: Terminal42\PasswordValidationBundle\Validation\Validator\MaximumLength
    tags:
      - { name: terminal42_password_validation.validator, alias: maximum_length }
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.validator.required_characters:
    class: Terminal42\PasswordValidationBundle\Validation\Validator\RequiredCharacters
    tags:
      - { name: terminal42_password_validation.validator, alias: required_characters }
    arguments:
      ['@terminal42_password_validation.validator_configuration']

  terminal42_password_validation.listener.force_password_change_frontend:
    class: Terminal42\PasswordValidationBundle\EventListener\ForcePasswordChangeFrontendListener
    arguments:
      - '@contao.framework'
      - '@security.token_storage'
      - '@security.authentication.trust_resolver'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
